feat: Implement Contribute service page
valory-xyz/olas-website pull request #96
Opened 2024-08-06 10:03 UTC by mohandast52

- [Contribute page](https://olas-website-git-mohan-contribute-service-autonolas.vercel.app/contribute#what-is-olas-contribute-service)

https://github.com/user-attachments/assets/f0b44476-99ee-4084-809c-bf817e861c44

2024-08-07 07:28 UTC, Tanya-atatakai commented on pages/contribute.jsx
> +        <Button variant="default" size="xl" className="mt-6 w-full md:w-auto">
can we pass `asChild` prop to the button? so the whole buttons is a link, but not only the text

2024-08-07 07:28 UTC, Tanya-atatakai commented on pages/contribute.jsx
> +                  // textShadow: '-1px -1px 0 #a855f7, 1px -1px 0 #a855f7, -1px 1px 0 #a855f7, 1px 1px 0 #a855f7',
works fine for me, can you elaborate please? and can we remove the code if it's not working?

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/74e0f1a4-6a30-491c-8a33-34351c3913e8">

2024-08-07 07:28 UTC, Tanya-atatakai commented on pages/contribute.jsx
> +            onClick={() => window.open(
can we use anchor tag instead?

2024-08-07 07:38 UTC, Tanya-atatakai commented on pages/contribute.jsx
> +                  // textShadow: '-1px -1px 0 #a855f7, 1px -1px 0 #a855f7, -1px 1px 0 #a855f7, 1px 1px 0 #a855f7',
ahh see, sharp eye 👍

2024-08-07 07:38 UTC, Tanya-atatakai approved these changes

2024-08-07 17:00 UTC, oaksprout approved these changes

2024-08-07 17:03 UTC, Tanya-atatakai requested changes
just realised this page should point to the `/services/contribute` and the old one can be removed

2024-08-07 17:10 UTC, Tanya-atatakai commented
ah sorry, ok

2024-08-07 17:10 UTC, Tanya-atatakai approved these changes

2024-08-08 09:57 UTC, truemiller approved these changes

2024-08-08 09:58 UTC, merged